FORMAT: 1A
HOST: http://www.google.com

# SchmaInfo API
Schema-Info API ...

## SchemaInfo collection [/schemaInfos]
### List all schemaInfo [GET]

+ Response 200 (application/json)

        [{ "name":"123", "namespace": "testNamespace"}]
        
## Number of schema-Infos [/schemaInfos/count?offset,limit]
### Get number of schemaInfos [GET]
+ Parameters
    + offset (optional, number, `1`) ... offset
    + limit (optional, number, `10`) ... limit
+ Response 200 (application/json)

        [{1}]
