FORMAT: 1A
HOST: http://www.google.com

# SchmaInfo API
Schema-Info API ...

## SchemaInfo collection [/schemaInfos?offset=&limit=]
### List all schemaInfo [GET]
+ Parameters
    + offset (optional, number, `1`) ... offset
    + limit (optional, number, `10`) ... limit

+ Response 200 (application/json)

        {
        "name": "string",
        "namespace": "string",
        "schemaVersionInfo": [{
        "status": "string",
        "version": "string"
        }
        ]
        }
        
## Number of schema-Infos [/schemaInfos/count]
### Get number of schemaInfos [GET]
+ Response 200 (application/json)

        [{1}]
