FORMAT: 1A

# Customer and Partner Management API
Customer and Partner Management (CPM) RESTful webservices.

# Group Customer
Customer related resources of customer API.

## Customer [/customers/{id}]
Read and create a new customer

+ Model (application/json)

    + Body

            {
                "CreateCustomerResponse" : {
                        "party" : {
                                        "partyId" : "string",
                                        "validFor" : {
                                                        "start" : "dateTime",
                                                        "end" : "dateTime"
                                                     }
                        },
                        "customer" : {
                                        "customerId" : "string",
                                        "customerStatus" : [
                                                        {
                                                            "status" : "string",
                                                            "statusReason" : "string",
                                                            "validFor" : {
                                                                            "start" : "dateTime",
                                                                            "end" : "dateTime"
                                                                         }
                                                        }
                                        ],
                                        "customerStatusOld" : "string",
                                        "billingAccounts" : [{
                                                                "isPrimary" : "boolean"
                                                             }],
                                        "agreements" : [{
                                                            "agreementPeriod" : {
                                                                            "start" : "dateTime",
                                                                            "end" : "dateTime"
                                                            },
                                                            "agreementDocumentNumber" : "string",
                                                            "agreementStatus" : "string",
                                                            "agreementStatusReason" : "string",
                                                            "partyInteractionRoles" : [{
                                                                                "interactionRole" : "string",
                                                                                "partyRole" : "string"
                                                            }]
                                                        }],
                                        "customerIDExternal" : "string"
                        }
        
                                        }
            }

            
### Create a new customer [PUT]
create a new customer


+ Request (application/json)

            {
                "CreateCustomerRequest": {
                
                    "party" : {
                    "partyId" : "string",
                    "validFor" : {
                                    "start" : "dateTime",
                                    "end" : "dateTime"
                                 }
                    },
                    "customer" : {
                                    "customerId" : "string",
                                    "customerStatus" : [{
                                                            "status" : "string",
                                                            "statusReason" : "string",
                                                            "validFor" : {
                                                                            "start" : "dateTime",
                                                                            "end" : "dateTime"
                                                            }
                                                    }
                                    ],
                                    "customerStatusOld" : "string",
                                    "billingAccounts" : [{
                                                            "isPrimary" : "boolean"
                                                    }
                                    ],
                                    "agreements" : [{
                                                        "agreementPeriod" : {
                                                                        "start" : "dateTime",
                                                                        "end" : "dateTime"
                                                        },
                                                        "agreementDocumentNumber" : "string",
                                                        "agreementStatus" : "string",
                                                        "agreementStatusReason" : "string",
                                                        "partyInteractionRoles" : [{
                                                                                        "interactionRole" : "string",
                                                                                        "partyRole" : "string"
                                                                        }
                                                        ]
                                        }
                                    ],
                                    "customerIDExternal" : "string"
                    }
        
                }
            }


+ Response 200

    [Customer][]
    

### Retrieve a customer [GET]
Retrieves a customer 

+ Parameters
    + id (string) ... ID of the customer.
    
+ Response 200 (application/json)
    
            {
                "ReadCustomerResponse": {
                                           "party":    {
                                              "partyId": "CC2C2601E874473AB9AE2A349E1CBE3E",
                                              "validFor":       {
                                                 "start": "2013-12-10T13:30:07.000Z",
                                                 "end": "2014-10-06T13:30:07.000Z"
                                              }
                                           },
                                           "customer":    {
                                              "partyRoleId": "E374C20F83B943F5BADEF30CB0D77795",
                                              "validFor":       {
                                                 "start": "2013-12-10T13:30:07.000Z",
                                                 "end": "2014-10-06T13:30:07.000Z"
                                              },
                                              "status": "active",
                                              "partyRoleType": "Customer",
                                              "statusReason": "activation",
                                              "customerId": "E374C20F83B943F5BADEF30CB0D77795",
                                              "customerStatus": "active",
                                              "billingAccounts": [      {
                                                 "name": "421386678607",
                                                 "status": "active",
                                                 "type": "BillingAccount",
                                                 "accountId": "BE95B0D001184F2E87E779E0A5A5E0D5",
                                                 "accountIDExternal": "1355",
                                                 "isPrimary": true
                                              }],
                                              "agreements": {},
                                              "customerIDExternal": "1355"
                                        }
                }
            
            }

